### ISSUE TITLE
Failed to execute 'text' on 'Response': body stream already read

### ISSUE THREAD

**Issue by cclement-perrin-acoss** [mulbc/vaultPass#28] opened 2022-02-18 09:05 UTC
**Describe the bug**
When trying to log on Vault server with LDAP authent, I have got an error message: `Failed to execute 'text' on 'Response': body stream already read`.

The only option is "Logout". Iam not able to search any secret.

**Expected behavior**
No error message

**Browser (please complete the following information):**
 - OS: Win10
 - Type Chrome
 - Version: Version 98.0.4758.102

**Comment by ticktostick** [comment] 2022-04-21 16:40
same problem here

chrome:100.0.4896.127
released:2.3
Vault 1.10.0

**Comment by mwxp06** [comment] 2022-05-06 08:46
Same problem :(
@mulbc Do you have any plan with this tool, os id dead now?

Thank you

**Comment by tamere-allo-peter** [comment] 2022-05-19 04:05
Same problem here.

VaultPass 2.3, with Chrome 101.0.4951.64 (Build officiel) (64 bits) on System: Kernel: 5.4.0-110-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 Desktop: Xfce 4.14.2 tk: Gtk 3.24.13 wm: xfwm4 dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 

LDAP auth works fine from Vault's GUI or Vault's API.
Vault installed from docker.io/hashicorp/vault

**Comment by ticktostick** [comment] 2022-05-30 06:40
The erro has gone
the problem is solved its working now

**Comment by mulbc** [comment] 2022-05-30 07:13
Thanks for confirming! I'll close the issue then

**Closed by mulbc** 2022-05-30 07:13 UTC
Labels: bug
